spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cars
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    serialization:
      indent-output: true
server:
  port: 8081
  error:
    include-message: always
